name: Release to NPM

on: [push, workflow_dispatch]

env:
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install dependencies
        run: yarn
      - name: Publish package
        run: yarn publish --access public --tag ${{ env.VERSION }} --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}