name: Release to NPM

on: [push, workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install dependencies
        run: yarn
      - name: Build Package
        run: yarn build
      - name: Publish package
        run: yarn publish --access public --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}